name: Distribute to Firebase App Distribution

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} # If there are changes since the last run
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install firebase tool
        run: |
          yarn global add firebase-tools
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: distribute to Firebase App Distribution
        run: bundle exec fastlane bundle_for_distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          GIT_COMMIT: ${{ steps.short-sha.outputs.sha }}
          BUILD_NUMBER: ${{ github.run_number }}
